# Generated by Django 5.2.6 on 2025-09-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('funcao', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('obra', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
