# Generated by Django 5.2.6 on 2025-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('FE', 'Férias'), ('LI', 'Licença'), ('AF', 'Afastado do INSS'), ('AV', 'Aviso'), ('AC', 'Admitido em casa'), ('FO', 'Folga'), ('EC', 'Em contratação')], default='A', max_length=2),
        ),
    ]
