# Generated by Django 5.2.6 on 2025-09-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default='', max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
    ]
