# Generated by Django 5.2.6 on 2025-09-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nivel_funcao',
            field=models.IntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3'), (4, 'Nível 4'), (5, 'Nível 5')], default=1),
        ),
    ]
