# Generated by Django 5.2.6 on 2025-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_funcionario_nivel_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
