# Generated by Django 5.2.6 on 2025-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_funcionario_bairro_funcionario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
