# Generated by Django 5.2.6 on 2025-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_funcionario_complemento_funcionario_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='contrato_trabalho',
            field=models.FileField(blank=True, null=True, upload_to='contratos_trabalho/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ordem_servico',
            field=models.FileField(blank=True, null=True, upload_to='ordens_servico/'),
        ),
    ]
