# Generated by Django 5.2.6 on 2025-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_funcionario_contrato_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
