# Generated by Django 5.2.6 on 2025-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
