# Generated by Django 5.2.6 on 2025-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
